name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: justgook/setup-elm@1.2.0

      - name: Build
        run: |
          mkdir ./public
          elm make --optimize src/Main.elm --output ./public/index.html
          elm make --debug src/Main.elm --output ./public/debug.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
